image: ruby:2.7

stages:
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

cache:
  paths:
    - vendor/


before_script:
  - gem install bundler
  - bundle config set --local path 'vendor'

build-job:
  stage: build
  tags:
    - hva
  script:
    - bundle exec jekyll build -d build
  artifacts:
    paths:
      - build

deploy-job:
  tags:
    - hva
  stage: deploy
  script:
    - bundle exec jekyll build -d deploy
  artifacts:
    paths:
      - deploy
